package com.tagforge.device.controller;

import com.tagforge.device.dto.CreateDeviceRequest;
import com.tagforge.device.dto.DeviceResponse;
import com.tagforge.device.entity.Device;
import com.tagforge.device.service.DeviceService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import jakarta.validation.Valid;
import org.springframework.http.ProblemDetail;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.util.UriComponentsBuilder;

import java.net.URI;
import java.util.UUID;

/** Translates HTTP only. No business rules, no transactions, no error handling. */
@RestController
@RequestMapping("/devices")
public class DeviceController {

    private static final String JSON = "application/json";
    private static final String PROBLEM_JSON = "application/problem+json";

    private final DeviceService deviceService;

    public DeviceController(DeviceService deviceService) {
        this.deviceService = deviceService;
    }

    /**
     * The statuses below are not inferable from the signature: 201 is chosen at
     * runtime, and 400 comes from the exception handler rather than this method.
     */
    @Operation(summary = "Create a device",
            description = "The id is generated by the server; the request body carries only a name.")
    @ApiResponses({
            @ApiResponse(responseCode = "201", description = "Created. Location header holds the new device URL.",
                    content = @Content(mediaType = JSON,
                            schema = @Schema(implementation = DeviceResponse.class))),
            @ApiResponse(responseCode = "400", description = "Name missing or blank",
                    content = @Content(mediaType = PROBLEM_JSON,
                            schema = @Schema(implementation = ProblemDetail.class)))
    })
    @PostMapping
    public ResponseEntity<DeviceResponse> create(@Valid @RequestBody CreateDeviceRequest request,
                                                 UriComponentsBuilder uriBuilder) {
        Device device = deviceService.create(request.name());

        // Injected per request, so Location is correct behind a proxy or on a non-default port.
        URI location = uriBuilder.path("/devices/{id}")
                .buildAndExpand(device.getId())
                .toUri();

        return ResponseEntity.created(location).body(DeviceResponse.from(device));
    }

    @Operation(summary = "Fetch a device by id")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Found",
                    content = @Content(mediaType = JSON,
                            schema = @Schema(implementation = DeviceResponse.class))),
            @ApiResponse(responseCode = "404", description = "No device with that id",
                    content = @Content(mediaType = PROBLEM_JSON,
                            schema = @Schema(implementation = ProblemDetail.class)))
    })
    @GetMapping("/{id}")
    public ResponseEntity<DeviceResponse> get(@PathVariable UUID id) {
        return ResponseEntity.ok(DeviceResponse.from(deviceService.findById(id)));
    }

    /**
     * 204 rather than 200: there is nothing useful to return, and an empty body
     * with a 200 invites clients to look for one.
     *
     * An unknown id is 404 rather than a silent 204, so a caller can distinguish
     * "deleted" from "was never there" -- worth more here than strict idempotency,
     * since the simulator uses it to clean up devices it believes it created.
     */
    @Operation(summary = "Delete a device",
            description = "Removes the device row. Its telemetry is left in place and "
                    + "removed by retention; nothing joins to device and ingestion "
                    + "rejects unknown ids, so orphaned readings are inert.")
    @ApiResponses({
            @ApiResponse(responseCode = "204", description = "Deleted"),
            @ApiResponse(responseCode = "404", description = "No device with that id",
                    content = @Content(mediaType = PROBLEM_JSON,
                            schema = @Schema(implementation = ProblemDetail.class)))
    })
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable UUID id) {
        deviceService.delete(id);
        return ResponseEntity.noContent().build();
    }
}
